[system]
network_command = "systemctl restart dhcpcd"
program_dir = "/home/berri/Documents/coding/get-shit-done"

[blocklist]
websites = ["discord.com", "www.reddit.com", "gbatemp.net", "www.facebook.com", "www.tumblr.com", "tech.lgbt", "x.com", "www.instagram.com", "www.youtube.com"]
programs = ["Discord", "steam"]

